package a_ejemplo_banco;

/*LINKEDLIST
 * SE USA CUANDO SE VAN A ELIMINAR O AGREGAR MUCHOS ELEMENTOS YA QUE
 * ES MAS EFICIENTE QUE UN ARRAY LIS
 * 
 * VENTAJAS
 * - ACCESO ALEATORIO
 * - ESTANORDENADAS (COLLECTION.SOT())
 * - AÑADIR / ELIMINAR SIN RESTRICCION
 * -LISTITERATOR MODIFICAR EN CUALQUIER MOMENTO
 * - SINTAXIS SIMILAR A ARRAY
 * 
 * DESVENTAJAS
 * - BAJO RENDIMIENTO EN OPERACIONES CONCRETAS
 * QUE SE RESOLVERIAN MEJOR CON OTRAS INTERFACES
 * 
 */



public class c_LinkendList {

}
